
DROP TABLE IF EXISTS PLACES;
DROP TABLE IF EXISTS GEOLOCATION;

CREATE TABLE GEOLOCATIONS(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    location VARCHAR(250) NOT NULL,
    longitude DOUBlE NOT NULL,
    latitude DOUBLE NOT NULL
)
CREATE TABLE PLACES (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    FOREIGN KEY(GEOLOCATION) REFERENCES GEOLOCATION(id)
  );



