
DROP TABLE IF EXISTS PLACES;
DROP TABLE IF EXISTS GEOLOCATIONS;

CREATE TABLE GEOLOCATIONS(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    location VARCHAR(250) NOT NULL,
    longitude DOUBlE NOT NULL,
    latitude DOUBLE NOT NULL
);
CREATE TABLE PLACES (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    location_id INT NOT NULL
  );

CREATE SEQUENCE GEOLOCATIONS_SEQUENCE_ID START WITH (select max(id) + 1 from GEOLOCATIONS);




